os:
  - linux
sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60
    --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --config gcc
  - gcc -v
  - g++ -v
  - cmake --version

script:
  - sh ./build.sh Debug build-debug
  - sh ./build.sh Release build-release
